name: import data

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  biotools:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push-biotools.outputs.commit_hash }}
    steps:
    - name: checkout contents repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: delete previous import branch
      run: git push origin --delete biotools-import-branch
    - name: Create and checkout feature branch
      run: git checkout -b biotools-import-branch
    - name: import bio.tools data from server
      uses: research-software-ecosystem/utils/biotools-import@main
      with:
        repo-user: ${{ secrets.GITHUB_USER }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit and Push Changes
      id: commit-and-push-biotools
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_user_name: Tools Platform Ecosystem bot
        commit_user_email: tpe-bot@github.com
        commit_author: Tools Platform Ecosystem bot <tpe-bot@github.com>
        commit_message: import bio.tools data on $(date)
        branch: biotools-import-branch
        create_branch: true
  openebench:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push-openebench.outputs.commit_hash }}
    steps:
    - name: checkout contents repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: delete previous import branch
      run: git push origin --delete openebench-import-branch
    - name: Create and checkout feature branch
      run: git checkout -b openebench-import-branch
    - name: import OpenEBench data from server
      uses: research-software-ecosystem/utils/openebench-import@main
      with:
        repo-user: ${{ secrets.GITHUB_USER }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit and Push Changes
      id: commit-and-push-openebench
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_user_name: Tools Platform Ecosystem bot
        commit_user_email: tpe-bot@github.com
        commit_author: Tools Platform Ecosystem bot <tpe-bot@github.com>
        commit_message: import OpenEBench data on $(date)
        branch: openebench-import-branch
        create_branch: true
  bioconda:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push-bioconda.outputs.commit_hash }}
    steps:
    - name: checkout contents repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: delete previous import branch
      run: git push origin --delete bioconda-import-branch
    - name: Create and checkout feature branch
      run: git checkout -b bioconda-import-branch
    - name: import bioconda data from server
      uses: research-software-ecosystem/utils/bioconda-import@main
      with:
        repo-user: ${{ secrets.GITHUB_USER }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit and Push Changes
      id: commit-and-push-bioconda
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_user_name: Tools Platform Ecosystem bot
        commit_user_email: tpe-bot@github.com
        commit_author: Tools Platform Ecosystem bot <tpe-bot@github.com>
        commit_message: import bioconda data on $(date)
        branch: bioconda-import-branch
        create_branch: true
  biii:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit-and-push-biii.outputs.commit_hash }}
    steps:
    - name: checkout contents repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: delete previous import branch
      run: git push origin --delete biii-import-branch
    - name: Create and checkout feature branch
      run: git checkout -b biii-import-branch
    - name: import biii data from server
      uses: research-software-ecosystem/utils/biii-import@main
      with:
        repo-user: ${{ secrets.GITHUB_USER }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit and Push Changes
      id: commit-and-push-biii
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_user_name: Tools Platform Ecosystem bot
        commit_user_email: tpe-bot@github.com
        commit_author: Tools Platform Ecosystem bot <tpe-bot@github.com>
        branch: biii-import-branch
        create_branch: true
  merge:
    runs-on: ubuntu-latest
    needs:
      - biotools
      - openebench
      - bioconda
      - biii
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Merge feature branches
        run: |
          git merge biotools-import-branch
          git merge openebench-import-branch
          git merge bioconda-import-branch
          git merge biii-import-branch
          git push origin master
  clean-branches:
    runs-on: ubuntu-latest
    needs:
      - merge
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Delete feature branches
        run: |
          git push origin --delete biotools-import-branch
          git push origin --delete openebench-import-branch
          git push origin --delete bioconda-import-branch
          git push origin --delete biii-import-branch
